title: RealBeauty
description: Software Engineering project work report - know what's really inside your personal care products
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: true
plugins:
  - jekyll-remote-theme
defaults:
  - scope:
      path: ""
    values:
      layout: default
